### ISSUE TITLE
When a form has more than one mandatory file upload field, only 1 file upload field needs a value for the form to submit.

### ISSUE THREAD

**Issue by gregeaton** [bboyle/form-validation#40]
Possible cause: the name attribute of each file upload field is identical so all files are included in the email attachment. This is (I believe) a requirement of file upload. Essentially it seems that file upload and the SWE mandatory script aren’t playing nice together.

**Comment by gregeaton** [comment]
See video: I DRIVE... \Self-Service\Ecology\Services\1-Tracking\File upload\test outcomes\error - submitted without all uploads selected.wmv

**Comment by bboyle** [comment]
This applies broadly to any form field that has a duplicate `@name`
See demo with duplicate `@name` on text input fields here: http://codepen.io/bboyle/pen/sjgyG/

Note: radio buttons use `@name` for grouping and are not affected.
